### ISSUE TITLE
Get this error when loading the resource

### ISSUE THREAD

**Issue by CryptoParts** [ImagicTheCat/vRP-TCG#1]
Error loading script server.lua in resource vRP_TCG: @vrp/lib/utils.lua:13: bad argument #1 to 'load' (function expected, got nil)
stack traceback:
        [C]: in function 'load'
        @vrp/lib/utils.lua:13: in function 'module'
        server.lua:7: in main chunk
Failed to load script server.lua.

**Comment by ImagicTheCat** [comment]
Not an help section, you probably messed up the config file.

**Comment by CryptoParts** [comment]
Not asking for help. Just letting you know..... This was on a fresh vrp server i test on. And saying "I" must of  messed up the config.... lol I didn't change anything!
