### ISSUE TITLE
Dont work for vrpex

### ISSUE THREAD

**Issue by Origintk** [ImagicTheCat/vRP-TCG#3]
338203] Await failure: server.lua:46: wrong number of arguments to 'insert'
[    338203] stack traceback:
[    338203]     [C]: in function 'table.insert'
[    338203]     server.lua:46: in function 'open_booster'
[    338203]     server.lua:83: in function 'open_user_booster'
[    338203]     server.lua:193: in upvalue 'ref'
[    338203]     citizen:/scripting/lua/scheduler.lua:337: in function citizen:/scripting/lua/scheduler.lua:336
[    338203]     [C]: in function 'xpcall'
[    338203]     citizen:/scripting/lua/scheduler.lua:336: in function citizen:/scripting/lua/scheduler.lua:335
[    338203] stack traceback:
[    338203]     citizen:/scripting/lua/scheduler.lua:577: in local 'cb'
[    338203]     modules/gui.lua:192: in local 'f'
[    338203]     [string "vrp/lib/Tunnel.lua"]:127: in upvalue 'handler'

**Comment by ImagicTheCat** [comment]
Fixed.
